name:                blogPosts
version:             0.1.0.0
github:              "Martinsl/blogPosts"
license:             BSD3
author:              "martinsl"
maintainer:          "example@example.com"
copyright:           "2020 martinsl"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Martinsl/blogPosts#readme>

dependencies:
- base >= 4.7 && < 5
- scalpel

library:
  source-dirs: src

executables:
  blogPosts-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blogPosts

tests:
  blogPosts-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blogPosts
